# Docker-Compose file for LPS Platform
version: '3.7'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - services/db/postgres-prod.env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  api:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: always
    expose:
      - 5000
    depends_on:
      - db
      - cache

  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - api

  cache:
    image: redis
    command: "redis-server"
    restart: always
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data: {}
  redis-data: {}