# Docker-Compose file for LPS Platform
version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - instance/env/postgres.env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: always
    expose:
      - 5000
    depends_on:
      - postgres

  nginx:
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

  cache:
    image: redis
    command: "redis-server"
    restart: always
    expose:
      - 6379
    volumes:
      - redis-data:/data
    depends_on:
      - postgres

volumes:
  postgres-data: {}
  redis-data: {}