"""reset migrations

Revision ID: 2a50af4313ac
Revises: 
Create Date: 2022-06-26 16:40:18.104496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a50af4313ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=11), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pswd_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_super', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('api_key', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('api_key')
    )
    op.create_table('units',
    sa.Column('unit_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('alert_mail', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_sms', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locator_points',
    sa.Column('point_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('point_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('unit_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locator_points')
    op.drop_table('units')
    op.drop_table('api_keys')
    op.drop_table('users')
    # ### end Alembic commands ###
