"""alert mail and sms migration

Revision ID: 8c774f74d480
Revises: 60657d09f074
Create Date: 2021-10-05 15:47:18.639490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c774f74d480'
down_revision = '60657d09f074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('alert_mail', sa.BOOLEAN(), nullable=True))
    op.add_column('units', sa.Column('alert_sms', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'alert_sms')
    op.drop_column('units', 'alert_mail')
    # ### end Alembic commands ###
