"""first migration

Revision ID: 94ee4bd6a597
Revises: 
Create Date: 2021-08-15 21:52:03.946862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94ee4bd6a597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locator_points',
    sa.Column('point_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('point_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locator_points')
    op.drop_table('units')
    # ### end Alembic commands ###
